-- MySQL Script generated by MySQL Workbench
-- Tue Dec 14 18:06:10 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Customer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `idCustomer` INT NOT NULL,
  `CustomerName` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `ItemBought` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `idCustomer_UNIQUE` (`idCustomer` ASC) VISIBLE,
  PRIMARY KEY (`idCustomer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Supplier` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Supplier` (
  `idSupplier` INT NOT NULL,
  `SupplierCompanyName` VARCHAR(45) NOT NULL,
  `SupplierAddress` VARCHAR(45) NOT NULL,
  `SuppierEmail` VARCHAR(45) NOT NULL,
  `Brand_idBrand` INT NOT NULL,
  PRIMARY KEY (`idSupplier`),
  UNIQUE INDEX `idSupplier_UNIQUE` (`idSupplier` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Computer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Computer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Computer` (
  `idComputer` INT NOT NULL,
  `Computermodel` VARCHAR(45) NOT NULL,
  `Computerprice` DECIMAL NOT NULL,
  `ComputerRam` INT NOT NULL,
  `ComputerProcessor` VARCHAR(45) NOT NULL,
  `Brand_idBrand` INT NOT NULL,
  `Supplier_idSupplier` INT NOT NULL,
  PRIMARY KEY (`idComputer`),
  INDEX `fk_Computer_Supplier1_idx` (`Supplier_idSupplier` ASC) VISIBLE,
  CONSTRAINT `fk_Computer_Supplier1`
    FOREIGN KEY (`Supplier_idSupplier`)
    REFERENCES `mydb`.`Supplier` (`idSupplier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`order` ;

CREATE TABLE IF NOT EXISTS `mydb`.`order` (
  `idorder` INT NOT NULL,
  `taken_date` DATE NOT NULL,
  `dispatched_date` DATE NOT NULL,
  `invoiced_date` DATE NOT NULL,
  `Customer_Computer_Employee_idEmployee` INT NOT NULL,
  `Customer_idCustomer` INT NOT NULL,
  `Computer_idComputer` INT NOT NULL,
  PRIMARY KEY (`idorder`),
  INDEX `fk_order_Customer1_idx` (`Customer_Computer_Employee_idEmployee` ASC, `Customer_idCustomer` ASC) VISIBLE,
  INDEX `fk_order_Computer1_idx` (`Computer_idComputer` ASC) VISIBLE,
  CONSTRAINT `fk_order_Customer1`
    FOREIGN KEY (`Customer_idCustomer`)
    REFERENCES `mydb`.`Customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_Computer1`
    FOREIGN KEY (`Computer_idComputer`)
    REFERENCES `mydb`.`Computer` (`idComputer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
